# Generated by Django 3.0.7 on 2020-06-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(max_length=20, null='active'),
            preserve_default='active',
        ),
    ]
